# **<span style="color: yellow;">Bibliothèque et Package 🗒️:</span>**

En Python, bibliothèques et packages sont des concepts liés, mais avec quelques différences :

1. Bibliothèque (Library) :
Une bibliothèque est un ensemble de modules Python qui fournissent des fonctionnalités spécifiques. Elle peut contenir plusieurs modules et parfois même des packages. Par exemple, numpy, pandas et matplotlib sont des bibliothèques populaires pour la manipulation de données et le calcul scientifique.


2. Package :
Un package est une structure qui permet d'organiser des modules Python dans un répertoire. Il contient généralement un fichier spécial _init_.py (même s'il n'est plus obligatoire depuis Python 3.3). Un package peut contenir plusieurs sous-packages et modules.

Exemple de structure de package :

my_package/

├── _init_.py

├── module1.py

├── module2.py

├── subpackage/

    ├── _init_.py

    ├── submodule1.py




Différence clé :

Une bibliothèque est un ensemble de modules (et parfois de packages) offrant des fonctionnalités spécifiques.Un package est une structure organisationnelle qui permet de grouper plusieurs modules sous un même nom.


# *Installation d'une bibliothèque ou d'un package python💡*

👉 Ouvrir le terminal ou l'invite de commandes 

👉Utiliser la commande "pip install nom_du_package"
        Exemple : pip install numpy

👉Importer le package dans un script Python pour vérifier.


# **1. Création et manipulation avancée de tableaux NumPy💡**



1.1 Types de données dans NumPy

NumPy optimise la mémoire en utilisant des types de données spécifiques comme int32, float64, etc.



In [1]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)  # Tableau d'entiers 32 bits
print(arr.dtype)


int32


Astuce : On peut convertir un type avec .astype().

In [2]:
arr_float = arr.astype(np.float64)  # Conversion en float64
print(arr_float.dtype)


float64



    Au lieu de créer un tableau manuellement, NumPy offre des méthodes pour générer des tableaux rapidement :

👉 np.zeros((m, n)) : crée un tableau de zéros.

👉 np.ones((m, n)) : crée un tableau de 1.

👉 np.full((m, n), valeur) : crée un tableau rempli avec une valeur donnée.

👉 np.eye(n) : crée une matrice identité.

👉 np.linspace(start, stop, num) : crée un tableau avec num valeurs uniformément espacées entre start et stop.

👉 np.arange(start, stop, step) : crée un tableau avec des valeurs espacées de step.






In [6]:
arr1 = np.zeros((2, 3))   # Tableau de zéros 2x3
arr2 = np.linspace(0, 10, 5)  # Cinq valeurs entre 0 et 10
arr3 = np.arange(1, 10, 2)  # Valeurs de 1 à 9 avec un pas de 2

print(".....arr1...... \n",arr1)
print("\n.....arr2...... \n",arr2)
print("\n.....arr3...... \n",arr3)


.....arr1...... 
 [[0. 0. 0.]
 [0. 0. 0.]]

.....arr2...... 
 [ 0.   2.5  5.   7.5 10. ]

.....arr3...... 
 [1 3 5 7 9]


# **2. Indexation et Slicing avancés 💡**

2.1 Indexation booléenne

On peut extraire des valeurs spécifiques d’un tableau en utilisant des conditions.


In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # Retourne [30 40 50]


[30 40 50]


2.2 Indexation avec listes d'indices

On peut extraire des éléments spécifiques en donnant une liste d'indices.



In [11]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])  # [10 30 50]


[10 30 50]


# **3. Opérations mathématiques avec NumPy 💡**



3.1 Opérations élémentaires

On peut faire des opérations élément par élément.



In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(".....a + b....\n",a + b)  # [5 7 9]
print("\n.....a * b....\n",a * b)  # [4 10 18]
print("\n.....a**2....\n",a ** 2) # [1 4 9]


.....a + b....
 [5 7 9]

.....a * b....
 [ 4 10 18]

.....a**2....
 [1 4 9]


3.2 Fonctions mathématiques intégrées

NumPy propose des fonctions mathématiques optimisées.



In [15]:
arr = np.array([0, np.pi / 2, np.pi])
print(np.sin(arr))  # [0. 1. 0.]
print(np.log(np.array([1, 2, 3])))  # Logarithme naturel
print(np.exp(np.array([0, 1, 2])))  # Exponentielle


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0.         0.69314718 1.09861229]
[1.         2.71828183 7.3890561 ]


# **4. Manipulation de tableaux💡**

4.1 Changement de forme (reshape)

On peut modifier la forme d’un tableau sans en changer les valeurs.



In [16]:
arr = np.arange(1, 10)
reshaped = arr.reshape((3, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


4.2 Concaténation et empilement

On peut concaténer ou empiler des tableaux.



In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(np.vstack((a, b)))  # Empile verticalement
print("\n",np.hstack((a, b.T)))  # Empile horizontalement


[[1 2]
 [3 4]
 [5 6]]

 [[1 2 5]
 [3 4 6]]


# **5. Statistiques et agrégation💡**



NumPy permet d’effectuer des opérations statistiques rapidement.



In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Somme totale : ",arr.sum())  # Somme totale
print("\nMoyenne: ",arr.mean())  # Moyenne
print("\nEcart-type: ",arr.std())  # Écart-type
print("\nMinimum par ligne : ",arr.min(axis=1))  # Minimum par ligne
print("\nMaximum par colonne: ",arr.max(axis=0))  # Maximum par colonne


Somme totale :  21

Moyenne:  3.5

Ecart-type:  1.707825127659933

Minimum par ligne :  [1 4]

Maximum par colonne:  [4 5 6]


# **6. Applications avancées💡**

Génération de nombres aléatoires





NumPy permet de générer des nombres aléatoires pour la simulation et l’apprentissage automatique.

# *<span style="color: green;">Exercice 🗒️🖊️:</span>*

# *Partie 1*
Créer un tableau NumPy contenant les nombres de 1 à 20.

Extraire une sous-partie de ce tableau allant du 5e au 15e élément.

Redimensionner la sous-partie extraite pour qu'elle soit une matrice 2x5.

Calculer la somme de tous les éléments de cette matrice.

# *Partie 2*

Créer deux tableaux NumPy contenant 10 nombres aléatoires chacun.

Additionner ces deux tableaux élément par élément.

Appliquer une fonction logarithmique sur le tableau résultant.

Calculer la moyenne des éléments du tableau résultant.